version: '3.1'

services: 
    jenkins: 
        image: jenkins/jenkins:lts
        restart: always
        container_name: jenkins

        networks: 
            - jenkins-custom

        ports: 
            - 8080:8080
            - 50000:50000
        volumes: 
            - ./volume:/var/jenkins_home

        environment: 
            TZ: America/Sao_Paulo

networks: 
    jenkins-custom:
        driver: bridge